### PR TITLE
Zach/addnewedit

### PR DESCRIPTION
**Pull request by wibergln**

### CODE REVIEW

**Comment by ZachSand** [comment]
Looks good to me!

**Comment by wibergln** [comment]
Did you run it and see if everything looks okay?

**Comment by ZachSand** [comment]
On my emulator everything looks good. I'm able to change the description text, dismiss the keyboard, add an image, and select the "Done" or "Cancel" buttons. It also looks like the event was saved because when I start the app again I don't get the no_event_startup.xml layout which tells me there is an event saved for the user. 
My Android phone won't show up on my computer but i'm trying to test it on that now.

**Comment by wibergln** [comment]
Okay to merge?

**Comment by ZachSand** [comment]
Yep! I didn't see any errors when building and running on the emulator.

**Pull request merged**
